apiVersion: v1
kind: Service

metadata:
  name: cloudops-platform-service
  namespace: cloudops-platform

spec:
  selector:
    app: cloudops-platform

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP